### ISSUE TITLE
Requirement python constraint is not respected when resolving

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#141]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

We have a project, that requires python>=3.6, and we define a dependency that requires python=3.8:

```toml
[tool.pdm]
python_requires = ">=3.6"

[tool.pdm.dependencies]
vendoring = {version="*", marker="python_full_version~='3.8.0'"}
```

## Actual behavior

ResolutionImpossible

## Expected behavior

The dependency gets resolved successfully, with a marker.
