### ISSUE TITLE
Package is resolved with wrong marker if its grandparents have different markers.

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#170]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

Given the below dependency tree
```
A   B
 \ /
  C
  |
  D
```

If one resolves with:
```toml
[tool.pdm.dependencies]
A = "*"
B = {version = "*", marker = "python_version ~= '3.8'"}
```
B is only required under python 3.8, then the resolution result marks package `D` with `python_version >= '3.8' and python_version < '4.0'`, which is incorrect. In other words, the marker of `B` propagates to its grandchild `D`, but `A` fails to influence it.
