### ISSUE TITLE
Provide an option to export from pyproject.toml

### ISSUE THREAD

**Issue by rihkddd** [frostming/pdm#190]
## Steps to reproduce
The pyproject.toml file content is:
```toml
[tool]
[tool.pdm]
name = "test"
version = "0.0.1"
description = ""
author = " <>"
license = "MIT"
homepage = ""
python_requires = ">=3.7"

[tool.pdm.dependencies]
aiofiles = "<1.0.0,>=0.6.0"
certifi = "<2021.0.0,>=2020.12.5"
chardet = "<4.0.0,>=3.0.4"
concurrent-log-handler = "<1.0.0,>=0.9.19"
dbutils = "<3.0.0,>=2.0"
future = "<1.0.0,>=0.18.2"
grpcio-tools = "<2.0.0,>=1.34.0"
grpcio = "<2.0.0,>=1.34.0"
h11 = "<1.0.0,>=0.9.0"
httpcore = "<1.0.0,>=0.11.1"
httptools = "<1.0.0,>=0.1.1"
httpx = "<1.0.0,>=0.15.4"
idna = "<3.0.0,>=2.10"
joblib = "<1.0.0,>=0.17.0"
loguru = "<1.0.0,>=0.5.3"
portalocker = "<3.0.0,>=2.0.0"
protobuf = "<4.0.0,>=3.14.0"
pyhive = "<1.0.0,>=0.6.3"
pymysql = "<1.0.0,>=0.10.1"
python-dateutil = "<3.0.0,>=2.8.1"
redis = "<4.0.0,>=3.5.3"
requests = "<3.0.0,>=2.25.0"
sanic = "<21.0.0,>=20.9.1"
sasl = "<1.0.0,>=0.2.1"
scikit-learn = "<1.0.0,>=0.23.2"
scipy = "<2.0.0,>=1.5.4"
six = "<2.0.0,>=1.15.0"
sniffio = "<2.0.0,>=1.2.0"
threadpoolctl = "<3.0.0,>=2.1.0"
thrift = "<1.0.0,>=0.13.0"
thrift-sasl = "<1.0.0,>=0.4.2"
ujson = "<5.0.0,>=4.0.1"
urllib3 = "<2.0.0,>=1.26.2"
uvloop = "<1.0.0,>=0.14.0"
numpy = "==1.19.1"
elasticsearch = "==7.9.1"

[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```
then export requirements on CentOS 7.
```shell 
pdm export --without-hashes -v
```
## Actual behavior

```
aiofiles==0.6.0
certifi==2020.12.5
chardet==3.0.4
colorama==0.4.4; sys_platform == "win32"
concurrent-log-handler==0.9.19
dbutils==2.0
elasticsearch==7.9.1
future==0.18.2
grpcio==1.34.0
grpcio-tools==1.34.0
h11==0.9.0
httpcore==0.11.1
httptools==0.1.1
httpx==0.15.4
idna==2.10
joblib==0.17.0
loguru==0.5.3
multidict==5.0.0
numpy==1.19.1
portalocker==2.0.0
protobuf==3.14.0
pyhive==0.6.3
pymysql==0.10.1
python-dateutil==2.8.1
pywin32==300; platform_system == "Windows"
redis==3.5.3
requests==2.25.0
rfc3986==1.4.0
rfc3986[idna2008]==1.4.0
sanic==20.9.1
sasl==0.2.1
scikit-learn==0.23.2
scipy==1.5.4
setuptools==51.0.0
six==1.15.0
sniffio==1.2.0
threadpoolctl==2.1.0
thrift==0.13.0
thrift-sasl==0.4.2
ujson==4.0.1
urllib3==1.26.2
uvloop==0.14.0
websockets==8.1
win32-setctime==1.0.3; sys_platform == "win32"
```
## Expected behavior
why it exports package like **pywin32** and packages which platform is **win32**?

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        0.12.0
Python Interpreter: /usr/local/bin/python3.7 (3.7.3)
Project Root:       /root/output
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-957.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Nov 8 23:39:32 UTC 2018",
  "python_full_version": "3.7.3",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.7",
  "sys_platform": "linux"
}
```
