### ISSUE TITLE
Environment variable to refer to the project root in pyproject.toml

### ISSUE THREAD

**Issue by uranusjr** [frostming/pdm#226]
## Is your feature request related to a problem? Please describe.

It is a common pattern for a (private) project to make maintainers pre-build in-house wheels, and satisfy project dependencies with them. These wheels are generally stored (ignored by VCS) with the project, but there’s not a good way to refer to them in configuration. Both the index section and direct URL specifiers require a `file://` URL, which in turn mandates an absolute path.

## Describe the solution you'd like

Automatically populate a variable `PROJECT_ROOT` when expanding values in `pyproject.toml` and `pdm.lock`. The value should be a POSIX-style absolute path (i.e. forward slash, even on Windows) that points to the directory containing the project’s `pyproject.toml` file.

An alternative solution would be allowing the user to set variables in `.pdm.toml`. Something like this:

```toml
# .pdm.toml
[variables]
PROJECT_ROOT = "/path/to/the/current/project"

[python]
path = "${PROJECT_ROOT}/.tox/python39"
```

```toml
# pyproject.toml
[[tool.pdm.source]]
url = "file://${PROJECT_ROOT}/index"
name = "local"

[project]
dependencies = [
    "corp-project-a",  # Will be pulled from "local".
    "corp-project-b @ file://${PROJECT_ROOT}/wheels/crop_project_b-1.0-py3-non-any.whl",
]
```

Not matter the solution, the variable should only be injected on lock and install time, *not* during `pdm run`.

**Comment by frostming** [comment]
> Both the index section and direct URL specifiers require a file:// URL, which in turn mandates an absolute path.

True, it would be a good supplement as users can't use `./path` in PEP 508 specifiers.

Referring to this part:
```toml
[python]
path = "${PROJECT_ROOT}/.tox/python39"
```
Why do we need a dynamic interpreter path which will be injected on the fly, this also calls for injection during `pdm run` which violates your requirement.
