### ISSUE TITLE
markers are not merged when there are multiple sources

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#47]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
dependencies:
```toml
[tool.pdm.dependencies]
pytest="==4.6.*"
more-itertools=">=4.0.0,<6.0.0"
```
```bash
pdm lock
```

## Actual behavior

`more-itertools` has markers.

## Expected behavior

`more-itertools` has no marker.

## Environment Information

**pdm version**:

```bash
# Paste the output of `pdm info && pdm info --env` below:

```
